### PR TITLE
You can now set LED color order for 3 and 4 color strips

### PR DESCRIPTION
**Pull request by tonydew**
My SK6812 and WS2812b strips expect color info in G,R,B,W and G,R,B order, but the world (and the neopixel Color() method) works in RGB. Now you can specify the color order for 4 color LEDs like you could for 3 color previously, even in a multi strand setup.

Set your `strip_type` to one of the following to make it match the order your strip wants the colors provided in:

SK6812_STRIP_RGBW
SK6812_STRIP_RBGW
SK6812_STRIP_GRBW
SK6812_STRIP_GBRW
SK6812_STRIP_BRGW
SK6812_STRIP_BGRW
WS2811_STRIP_RGB
WS2811_STRIP_RBG
WS2811_STRIP_GRB
WS2811_STRIP_GBR
WS2811_STRIP_BRG
WS2811_STRIP_BGR

  The switch statement in ws2811.c is a little hokey, but I'm no C guru. If there's a better way, let me know.

### CODE REVIEW

**Comment by penfold42** [comment]
It looks like the datasheet i was using is incorrect - I found another hit on the arduino forums.

I suggest we remove the invalid SK6912 colour orders and only keep GRBW

Thoughts ?

**Comment by tonydew** [comment]
I know with the WS281x LEDs, the color order can change randomly from manufacturer to manufacturer, and even from order to order. No idea if the SK6812 will have the same issue.

The color ordering itself is pretty well handled, it's just the `switch()` I added inline that was kind of funky. However, looking back in the code history, I'm not sure it needs it. Look at the difference in ws2811.c here:

https://github.com/jgarff/rpi_ws281x/compare/master...tonydew:LED-ordering#diff-ad15add6b56882c8702200b9e4d154d8L645

Originally, it was just counting the size of the `color` array, no?

`for (j = 0; j < ARRAY_SIZE(color); j++)`

We could probably revert back to that, because since the `color` array has had white added, it will already be 4.

**Comment by tonydew** [comment]
Oh, wait. That will always be 4...

I wonder if strip_type should just be 'RGB' or 'RGBW' (and the ordered versions) instead. If they're all ws281\* based LEDs, we're just worried about the order of the R, G and B plus whether there is white or not, right?

The you could get the array size and LED_COLOURS value from the number of characters in the strip_type. That way, RGB strips would calculate the LED_BIT_COUNT correctly.

**Comment by penfold42** [comment]
With the 2811 it is just a chip with no LEDs so the order is solely up the the manufacturer.
With the 2812 and 6812 it should be fixed as the LEDs and chip are an integrated package

Let's leave them all in place and add another couple of defines that should work better. That is
#define WS2812 WS2811_GBR
#define SK6812 WS2811_GBR
#define SK6812W SK6812_GBRW

**Comment by tonydew** [comment]
Sorry I missed this. I'm on vacation and away from the laptop for a couple of days. I follow up when I'm back.

**Comment by penfold42** [comment]
It's cool - I've already done it and made a PR to get our work merged

**Pull request merged**
